In [1]:
#import sys
#{sys.executable} -m pip install torch torchvision torchaudio
import torch

see for the linear model....we take one input and predict one output ....now we have to train out network to do so



In [ ]:
X_test=[1, 2, 3, 4, 5, 6, 7, 8]
y_test=[32, 38, 45, 52, 60, 68, 75, 82]

In [299]:
x_test=torch.tensor(X_test)
y_test=torch.tensor(y_test)
w=torch.rand(1).requires_grad_(True)
b=torch.rand(1).requires_grad_(True)




C:\Users\nites\AppData\Local\Temp\ipykernel_22712\4004789347.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test=torch.tensor(y_test)


In [ ]:
loss=torch.zeros(1)
for i,j in zip(X_test,y_test):
    y_pred=i*w + b
    print(y_pred)
    loss+= (y_pred-j)**2
loss=loss/len(X_test)
loss=torch.sqrt(loss)
print(loss)
w.grad=None
b.grad=None
loss.backward()
w.data += -0.9*w.grad
b.data += -0.9*b.grad



tensor([24.6093], grad_fn=<AddBackward0>)
tensor([35.8691], grad_fn=<AddBackward0>)
tensor([47.1289], grad_fn=<AddBackward0>)
tensor([58.3887], grad_fn=<AddBackward0>)
tensor([69.6486], grad_fn=<AddBackward0>)
tensor([80.9084], grad_fn=<AddBackward0>)
tensor([92.1682], grad_fn=<AddBackward0>)
tensor([103.4280], grad_fn=<AddBackward0>)
tensor([11.8223], grad_fn=<SqrtBackward0>)


In [ ]:
# here the loss is of 3 types:
#  oscilaate: model is stuck between 2 values, so better reduce learnign rate to let him learn even the small steps on surface,here you are near the output.,model overshoots
#plateaus :  now the model is jumping with big steps..but soon the error becomes stuck as the model is on flat surface..to enhance the error ,let it too learn from small steps
#explodes : here the loss increasing too high ,gradients are too high...so the best is to reduce the learning rate immediately as soon as u face it


In [ ]:
# when to incrase the learning rate?...when model training just starts or the error is to slowly increasing